#!/usr/bin/bash

# $XDG_CONFIG_HOME/bspwm/bspwmrc
#
# bspwm configuration.

# Query xrdb for color, select last if there are multiples
xcolor() {
	xrdb -query                |
	grep -E "^(bspwm|\*)\.$1:" |
	sed -r "s/^[^:]+:\s+//"    |
	tail -n 1
}

# Application positioning rules
bspc rule -a Spotify       desktop=^9
bspc rule -a Brave-browser desktop=^2
bspc rule -a kitty --one-shot kitty

# Startup basic applicaitons
xrdb       ~/.config/X11/Xresources
setxkbmap  -option "ctrl:swapcaps"
xsetroot   -cursor_name left_ptr
polybar    -r aeryxium &
lxpolkit   &
picom      &
sxhkd      &
mpd-mpris  &
playerctld daemon
feh        --no-fehbg --bg-fill --randomize /usr/share/wallpapers/**

# Startup user applicatoins if they aren't already running
pgrep kitty   >/dev/null || kitty &
pgrep spotify >/dev/null || spotify &
pgrep brave   >/dev/null || brave --start-maximized &

# Set desktop names
bspc monitor -d ᚠ ᚢ ᚦ ᚩ ᚱ ᚳ ᚷ ᚹ ᚻ

# Configure options
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config ignore_ewmh_focus    true
bspc config gapless_monocle      false
bspc config border_width         2
bspc config split_ratio          0.52
bspc config window_gap           $(xcolor gap)
bspc config top_padding          $(xcolor panelGap)
bspc config focused_border_color $(xcolor activeColor)
bspc config active_border_color  $(xcolor normalColor)
bspc config normal_border_color  $(xcolor normalColor)

# Set initial layouts to tall
for i in $(bspc query -D --names); do
	bsp-layout set tall "$i" -- --master-size 0.6
done
